// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt8J_0YRRruJWexIqTyRjaGnqK_olMFB4',
    appId: '1:573895903426:web:d48db6f37b2a65a854535b',
    messagingSenderId: '573895903426',
    projectId: 'doctalk-55afb',
    authDomain: 'doctalk-55afb.firebaseapp.com',
    storageBucket: 'doctalk-55afb.appspot.com',
    measurementId: 'G-STFSJX32H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGPsEEDIEUZH26o8C9QKs0OxP0xj-1Fc',
    appId: '1:573895903426:android:fb2245fcb3fb41ee54535b',
    messagingSenderId: '573895903426',
    projectId: 'doctalk-55afb',
    storageBucket: 'doctalk-55afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs0RmSP5Lj5ZJ_VCRvxjNpfR0Sjj84n6Q',
    appId: '1:573895903426:ios:a86786435997153d54535b',
    messagingSenderId: '573895903426',
    projectId: 'doctalk-55afb',
    storageBucket: 'doctalk-55afb.appspot.com',
    iosBundleId: 'com.example.godrage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAw7mK12TcqUKcuyPeVh_DR3PVei5CkeY',
    appId: '1:233917914772:ios:be8e842e203ecdcf511e81',
    messagingSenderId: '233917914772',
    projectId: 'god-rage-aaca3',
    databaseURL: 'https://god-rage-aaca3-default-rtdb.firebaseio.com',
    storageBucket: 'god-rage-aaca3.appspot.com',
    iosClientId: '233917914772-89jkuj766qj9nbdrckva16n7bsdhtidg.apps.googleusercontent.com',
    iosBundleId: 'com.example.godrage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMAo8Pq3b7r7sgQwOq2sF3ZDlZJnSTYK0',
    appId: '1:233917914772:web:66d2887afdd4c752511e81',
    messagingSenderId: '233917914772',
    projectId: 'god-rage-aaca3',
    authDomain: 'god-rage-aaca3.firebaseapp.com',
    databaseURL: 'https://god-rage-aaca3-default-rtdb.firebaseio.com',
    storageBucket: 'god-rage-aaca3.appspot.com',
    measurementId: 'G-VWEEQHVMH3',
  );

}